version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    volumes: 
      - .:/app

  db:
    image: mysql
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: newuser 
      MYSQL_PASSWORD: newpassword
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  tests:
    build: ./app
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - .:/app
    command: ["pytest","./app/tests/test.py"]